version: '3.4'

services:
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
       - MONGO_URI=mongodb://mongodb:27017/user
    ports:
      - 3000:3000
